name: sparse-dev
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python
  - pip
  - numpy
  - numba
  - scipy
  - dask
  - pytest
  - pytest-cov
  - pytest-xdist
  - pip:
    - finch-tensor>=0.1.31
    - finch-mlir>=0.0.2
    - pytest-codspeed
